typedef enum : int {
    HAMPLAYER_RENDER_VIEW_TYPE_UNSPECIFIED = 0,
    HAMPLAYER_RENDER_VIEW_TYPE_EAGL = 1,
    HAMPLAYER_RENDER_VIEW_TYPE_METAL = 2,
    HAMPLAYER_RENDER_VIEW_TYPE_SBDL = 3,
    HAMPLAYER_RENDER_VIEW_TYPE_IOSURFACE = 4,
    HAMPLAYER_RENDER_VIEW_TYPE_IOSURFACE_MAIN_THREAD = 5,
    HAMPLAYER_RENDER_VIEW_TYPE_SBDL_SAMPLE_BUFFER = 6,
} HAMPlayerRenderViewType;
